### ISSUE TITLE
Error when Importing TSCV Gapwalkforward

### ISSUE THREAD

**Issue by mksamelson** [WenjieZ/TSCV#39] opened 2021-08-09 21:35 UTC
Using TSCV Gapwalkforward successfully with Python 3.7.

Suddenly getting following error:

ImportError                               Traceback (most recent call last)
<ipython-input-9-d7e76ef834f7> in <module>
     41 #Modeling
     42 
---> 43 from tscv import GapWalkForward
     44 from sklearn.utils import shuffle
     45 from sklearn.model_selection import KFold

~\Anaconda3\envs\py37\lib\site-packages\tscv\__init__.py in <module>
----> 1 from .split import GapCrossValidator
      2 from .split import GapLeavePOut
      3 from .split import GapKFold
      4 from .split import GapWalkForward
      5 from .split import gap_train_test_split

~\Anaconda3\envs\py37\lib\site-packages\tscv\split.py in <module>
      7 
      8 import numpy as np
----> 9 from sklearn.utils import indexable, safe_indexing
     10 from sklearn.utils.validation import _num_samples
     11 from sklearn.base import _pprint

ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'

Any insight?  I get this when simply importing Gapwalkforward.

**Comment by mksamelson** [comment] 2021-08-09 21:56
This seems to be an issue with Scikit-learn 0.24.2.  When I roll back to Scikit-learn 0.23.2 it goes away

**Comment by WenjieZ** [comment] 2021-08-10 01:24
Duplicate of #12 and #24.

You can use the latest version of TSCV: 0.1.2, which is downloadable from both pip and conda-forge channel.

In this version, `GapWalkForward` is deprecated but not removed; it will issue a warning but still works fine. Also, I would like to recommend `GapRollForward`, which is a more flexible version of `GapWalkForwrad`. See https://tscv.readthedocs.io/en/latest/tutorial/roll_forward.html

Thank you for your support for TSCV.

**Closed** 2022-02-07 07:28 UTC
